### ISSUE TITLE
Too many query params in cURL example

### ISSUE THREAD

**Issue by lgierth** [ipfs/http-api-docs#1]
```
#### cURL Example

`curl -F file=@myfile "http://localhost:5001/api/v0/add?recursive=false&quiet=<value>&silent=<value>&progress=<value>&trickle=<value>&only-hash=<value>&wrap-with-directory=<value>&hidden=<value>&chunker=<value>&pin=true&raw-leaves=<value>"`
```

Some of these curl commands are pretty crowded :) We could limit it to include only required parameters.

**Comment by hsanjuan** [comment]
PRs welcome. I guess we can check if a type has a defined default, and use that to distinguish between mandatory and optional parameters. But I'm not sure that works for all cases.

**Comment by hsanjuan** [comment]
There's a commented block for this. But this essentially makes all arguments go away since options are usually not required and have defaults. I'll leave this as is, as the curl examples are more informative with options and people can just copy paste the start if they just need that.
