### ISSUE TITLE
Example on how to use block/put on both Node.js and on the browser?

### ISSUE THREAD

**Issue by MaiaVictor** [ipfs/http-api-docs#2]
Opening this issue as an request from a commenter on [this SO](https://stackoverflow.com/questions/45726591/how-do-i-publish-an-uint8array-to-ipfs-using-its-http-api-on-both-browser-and-n?noredirect=1#comment78411937_45726591) question. Would you guys kindly provide me an example on how to upload binary data from both Node.js and on the browser using the HTTP API? I'm particularly confused about the file format, and have been getting tons of different errors when trying to get it right on the past hours.

**Comment by MaiaVictor** [comment]
To be specific, I'm trying to simplify this library:

```javascript
const ipfsAPI = require("ipfs-api");
const ipfs = ipfsAPI("ipfs.infura.io", "5001", {protocol: "https"});
const Block = require("ipfs-block");
const multihash = require("multihashes");
const sha256 = require("js-sha256");
const bs58 = require("bs58");

// Uint8Array -> Promise String
const put = data =>
  ipfs.block.put(new Buffer(data));

// String -> Promise Uint8array
const get = cid =>
  ipfs.block.get(cid);

// Uint8Array -> String
const cid = data =>
  bs58.encode(multihash.encode(new Buffer(sha256(new Buffer(data)),"hex"), "sha2-256"));

module.exports = {put, get, cid}
```

When browserified, it has `1.6mb` - probably because of the imports. The ideal would be to just import [xhr](https://www.npmjs.com/package/xhr) and do the requests directly.

**Comment by diasdavid** [comment]
Hi @MaiaVictor, did you get to see the example here? https://github.com/ipfs/js-ipfs-api/tree/master/examples/upload-file-via-browser It shows how to upload a file.

I see that in your example code, you are trying to use the block API. Did you happen to go through https://github.com/ipfs/interface-ipfs-core/tree/master/API/block and https://github.com/ipfs/interface-ipfs-core/blob/master/src/block.js for some code examples?

Also, this repo is for the HTTP API docs, you are specially interested in js-ipfs-api, could you move this issue there? Thank you.
