### ISSUE TITLE
Recommended approach to HTTP API Authentication?

### ISSUE THREAD

**Issue by hhff** [ipfs/http-api-docs#22]
Hi!

I've been working on understanding the pinning concept, which I understand to be highly important for keeping content available on the network "in a permanent manner".

We have a thread going here: https://discuss.ipfs.io/t/trying-to-better-understand-the-pinning-concept/754

Ultimately what I've realized is that content added via a local daemon can be pinned on a remote VPS IPFS node (therefore making the content "permanent while the node is up") via the official API described in this repo, but unfortunately there's no API auth built in here (yet?)

Potentially NGINX can handle the reverse proxy, and Authentication, allowing one to pin content remotely, but I'd like to know the recommended approach here?

**Comment by hsanjuan** [comment]
Closing this as this is an old issue and does not direclty belong to http api docs generation. If needed, please continue discussion in https://discuss.ipfs.io. Thanks!
