### ISSUE TITLE
Remove files from "arguments" as they aren't query parameters

### ISSUE THREAD

**Issue by Stebalien** [ipfs/http-api-docs#25]
Currently, we list files along with the arguments. This is how the commands library thinks of them, but from an HTTP API standpoint, these "arguments" are actually multipart body pieces. We should remove body parts from the arguments list and move the description to the body section.

**Comment by hsanjuan** [comment]
It is just removing it from arguments, because there is a section about the request body already? https://docs.ipfs.io/reference/api/http/#api-v0-add

**Comment by hugomrdias** [comment]
yeah we need to skip in the arguments code, but we need to figure out a way to annotate the options that are meant to be the body of an http request. Can't be the name we already have file, value-time etc.

**Comment by hsanjuan** [comment]
I think in this case the `arg` is of type File. But afaik there is a single option like that at most. There cannot be several "request body" options right? (in general, ignore `/add` which requires specific documentation about the multipart parts).

**Comment by hugomrdias** [comment]
dht.put has an options `value-file` that is also meant to be in the body

**Comment by Stebalien** [comment]
@hugomrdias looks like DHT put is already in the request body (note: the API docs you're looking at are not up-to-date with the latest master).

https://gist.github.com/Stebalien/30699b795d1ed871c8021935f6632fa5#apiv0dhtput

So yeah, just removing it from the arguments and moving the help text down would fix this. I saw the arguments and completely glossed over the body section.

**Comment by hugomrdias** [comment]
@Stebalien but its also in the arguments in that link

also you merged a PR changing the cli arg name to value-file

**Comment by Stebalien** [comment]
Yep. I agree, we should remove it from the arguments.

**Comment by hsanjuan** [comment]
@johnnymatthews hey. If we are going to put any work into maintaining this library we need to make it produce exactly this https://docs-beta.ipfs.io/reference/http/api/#getting-started (https://github.com/ipfs/ipfs-docs-v2/blob/master/docs/reference/http/api.md). I think you made some changes manually. Do you plan to make more?

If not, I can port them back (we should generate docs for 0.4.23).

**Comment by johnnymatthews** [comment]
No I have no plans to add more changes in there, at least not in Q2.
