### ISSUE TITLE
serve content via webserver

### ISSUE THREAD

**Issue by preetsinojiya** [ipfs/http-api-docs#7]
I don't know the purpose of http-api-docs. But if it is for users to browse through the documentation locally and easily then I think it should also serve docs via webserver locally.
 
If it aligns with the philosophy of the existence of this repo then I can create PR  with changes.

**Comment by Mr0grog** [comment]
Sorry nobody’s been watching and replying here, @preetsinojiya. This repo is the code that generates the file that is served at https://ipfs.io/docs/api/ . It’s not necessarily intended for local use.
